json.id stat.id
json.user_id stat.user_id
json.game_id stat.game_id
json.avg_viewers stat.avg_viewers
json.time_streamed stat.time_streamed
json.followers_gained stat.followers_gained
json.review stat.review
json.user stat.user
json.game stat.game
json.created_at stat.created_at
json.updated_at stat.updated_at
